//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bible.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.chapter = new HashSet<chapter>();
        }
    
        public int id { get; set; }
        public string name_short { get; set; }
        public string name { get; set; }
        public int section_id { get; set; }
    
        public virtual section section { get; set; }
        public virtual ICollection<chapter> chapter { get; set; }
    }
}
