//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bible.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        public section()
        {
            this.book = new HashSet<book>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<book> book { get; set; }
    }
}
